version: 2.1

orbs:
  ruby: circleci/ruby@2.0.0
  macos: circleci/macos@2.3.4

jobs:
  integration_test:
    macos:
      xcode: 14.2.0
    resource_class: macos.m1.large.gen1
    steps:
      - macos/preboot-simulator:
          device: iPhone 14
          version: "16.2"
      - checkout
      - run: git submodule update --init --recursive
      - ruby/install-deps
      - run: bundle exec fastlane atb_uitests
      - run: bundle exec fastlane integration_tests
      - store_test_results:
          path: fastlane/report.xml

  unit_test:
    macos:
      xcode: 14.2.0
    resource_class: macos.m1.large.gen1
    steps:
      - macos/preboot-simulator:
          device: iPhone 14
          version: "16.2"
      - checkout
      - run: git submodule update --init --recursive
      - ruby/install-deps
      - run: bundle exec fastlane unit_tests
      - store_test_results:
          path: fastlane/report.xml

workflows:
  say-hello-workflow:
    jobs:
      - integration_test
      - unit_test
