version: 2.1

orbs:
  ruby: circleci/ruby@2.0.0
  macos: circleci/macos@2.3.4

jobs:
  unittest:
    macos:
      xcode: 14.2.0
    resource_class: macos.m1.large.gen1
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - ruby/install-deps
      - run: bundle exec fastlane unittests

  uitest:
    macos:
      xcode: 14.2.0
    resource_class: macos.m1.large.gen1
    steps:
      - macos/preboot-simulator:
          device: iPhone 14
          version: "16.2"
      - checkout
      - run: git submodule update --init --recursive
      - ruby/install-deps
      - run: bundle exec fastlane atb_uitests

  build:
    macos:
      xcode: 14.2.0
    resource_class: macos.m1.large.gen1
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - ruby/install-deps
      - run: bundle exec fastlane build

workflows:
  say-hello-workflow:
    jobs:
      - uitest
      - unittest
      - build:
          context:
            - mobile
